displayName=Party Defence Tracker
build=standard
author=Hyftar
version=1.2.2
support=
description=Calculates the defence of a boss based on defence-reducing special attacks
tags=party,defence,special,counter
plugins=com.partydefencetracker.DefenceTrackerPlugin